name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          yes | guardrails configure --token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNDk1MDA1MzYzNTE5OTY1Njg3MyIsImFwaUtleUlkIjoiMDM2MDJmNzctOGM0Yi00OGJjLWIzYTQtMDAyYWY4ZTAwY2JhIiwiaWF0IjoxNzMwODA2MDIwLCJleHAiOjE3Mzg1ODIwMjB9.whSWnZpcIIJvGQUXFXj4h3rwGLZ26LuXfVkZoQOypgo"
          pip install guardrails-ai==0.4.2
          guardrails hub install hub://guardrails/sensitive_topics
          guardrails hub install hub://guardrails/toxic_language
      
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      
      - name: Test with pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          coverage run -m pytest -v -s
      
      - name: Generate Coverage Report
        run: |
          coverage report -m